# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66bdff57a7a69a2bd571b98af12695ccab5db279259ca63e9dc8cd707446b39ab3535af2a7d1c7bd013706e7ca4c621f69b997e7b3e423c3818bdc7b424205eb

test:
  secret_key_base: 91158cf5959bf6e8e31bd01e828eb8731edebc0a06486641bc9a19713be2e762a9e406196199ed6679303bed9c2dcd9073ee89892198e1eaabcaadba163641dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
